services:
  - type: web
    name: clubcapy-server
    env: node
    buildCommand: npm install && npm run build --workspace=shared && npm run build --workspace=server
    startCommand: npm run start --workspace=server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
